# Generated by Django 4.0.4 on 2022-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime_Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('release_date', models.IntegerField(verbose_name='Год выпуска')),
                ('image', models.ImageField(upload_to='images/anime/%Y/%m/%d/', verbose_name='Картинка')),
                ('tags', models.ManyToManyField(to='anime.anime_tag', verbose_name='Тэги')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
