# Generated by Django 4.0.4 on 2022-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime_Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('release_date', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/anime/%Y/%m/%d/')),
                ('tags', models.ManyToManyField(to='anime.anime_tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
