# Generated by Django 4.0.4 on 2022-05-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='Отображается ли на сайте'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.ImageField(upload_to='anime/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
