# Generated by Django 4.0.4 on 2022-06-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_is_activated_alter_anime_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime_tag',
            options={'ordering': ['name']},
        ),
    ]
