# Generated by Django 4.0.4 on 2022-05-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_animeprofile_userlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animeprofile',
            options={'ordering': ['-userlink']},
        ),
        migrations.AlterField(
            model_name='animeprofile',
            name='username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Имя'),
        ),
    ]
