# Generated by Django 4.0.4 on 2022-05-26 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_is_activated_alter_anime_image'),
        ('profiles', '0004_alter_animeprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnimeRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.IntegerField(blank=True, verbose_name='Оценка')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime', verbose_name='Юзер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.animeprofile', verbose_name='Юзер')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
