# Generated by Django 4.0.4 on 2022-05-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_useranimerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranimerate',
            name='is_watched',
            field=models.BooleanField(default=0, verbose_name='Просмотренно?'),
            preserve_default=False,
        ),
    ]
