# Generated by Django 4.0.4 on 2022-06-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_useranimerate_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranimerate',
            options={'ordering': ['-rate', 'anime']},
        ),
        migrations.AlterField(
            model_name='useranimerate',
            name='rate',
            field=models.IntegerField(blank=True, default=0, verbose_name='Оценка'),
            preserve_default=False,
        ),
    ]
